### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jrscrs** [Aodrulez/blueTag#1]
Hi, 

Your installation manual states

`Download latest release version of blueTag ("blueTag-vX.uf2") from this github repository`

But there is no blueTag-vX.uf2 to be found. 

\- jrscrs

**Comment by EdwardGrayclaws** [comment]
https://github.com/Aodrulez/blueTag/releases/download/v1.0/blueTag-v1.uf2

**Comment by Aodrulez** [comment]
Thanks @EdwardGrayclaws for a quicker response than me :)
