### ISSUE TITLE
Question about pin assignments

### ISSUE THREAD

**Issue by ril3y** [Aodrulez/blueTag#4]
Sorry as I did not see a place to ask questions.  I am curious about why only 9 gpio are used? There are more pins available.  This is more than likely a dumb question but looking over the code I was not seeing why this would be.  Thanks for indulging the question!

**Comment by Aodrulez** [comment]
Hi ril3y,

That's a great question! It was purely a design choice considering there are now too many variants of dev boards with this micro-controller & is definitely not a hardware limitation. Feel free to increase this if required for your use-case.

**Comment by ril3y** [comment]
Thanks I appreciate it!  I wasn't sure I was just missing something obvious.  I am planning on expanding it to 16 channels.  Thanks!

**Comment by Gitbook-afine** [comment]
I think in many/most cases people will be using it with RPi Pico so maybe it would be good idea to have option/switch/version of release package specifically for Pico that would allow usage of all 16 channels? Also one small suggestion I think it would be a good idea to put picture of RPi Pico in the documentation with channels marked to help newcomers. I myself was little confused when starting with this great project and as they say one picture is worth more than thousand words xD Thanks for great tool.

**Comment by Aodrulez** [comment]
Having multiple branches for this specific use-case might be counter productive. Perhaps I can make it 16 channels by default. Will definitely add a picture of pins (channels) to use :)

**Comment by Aodrulez** [comment]
Done, please test the build & let me know if there are any errors.

**Comment by Aodrulez** [comment]
v1.0.2 addresses all of these, please test & report back any errors or issues you encounter if possible, would be helpful.
