### ISSUE TITLE
Would you consider dual license MIT or BSD?

### ISSUE THREAD

**Issue by DangerousPrototypes** [Aodrulez/blueTag#7]
Hello,

I'm porting blueTag to the Bus Pirate hardware as a stand alone alternative firmware.

In the future I plan to add a JTAG mode to the main Bus Pirate firmware with similar capabilities.  Would you consider dual licensing the project as GPL + BSD or MIT? Then I could integrate your source file directly and push any updates back to your repo.

Thank you for your consideration,
Ian

**Comment by Aodrulez** [comment]
Hi Ian,

I've switched the license to MIT. I've owned a BusPirate (v3?) for nearly a decade, and it's been a key part of my portable toolkit. I'd love to see this project contribute to yours!

![busPirate-Aod](https://github.com/user-attachments/assets/0597e497-2a25-4abd-b6af-ca8651331577)

**Comment by Aodrulez** [comment]
Hi Ian,

I've switched the license to MIT. I've owned a BusPirate (v3?) for nearly a decade, and it's been a key part of my portable toolkit. I'd love to see this project contribute to yours!

![busPirate-Aod (Small)](https://github.com/user-attachments/assets/1febe5a4-f806-4cc5-887f-489b694f6591)

**Comment by DangerousPrototypes** [comment]
Wow! Thank you much for allowing me to integrate it, and thank you so much for using a Bus Pirate :)

I will display your github credits in the command help.

**Comment by n3bojs4** [comment]
@DangerousPrototypes This deserves a Christmas present 🎁 🥳

**Comment by Aodrulez** [comment]
@n3bojs4 A bit of a late post, but I’m happy to share that I received the latest Buspirate package with all the accessories from Ian a few months ago! Made my day! :)
